### ISSUE TITLE
TimeSeries.resample method resampling over the current sample rate

### ISSUE THREAD

**Issue by sharanbngr** [gwpy/gwpy#1092]
Hello! 

TimeSeries.sample currently can resample at a sample rate (arbitrarily) higher than the current sample. I figured it out the hard way because I didn't check what the default frequency of the channel I was using was. 

I was wondering if this was the intended behaviour or an error in the code. If it is the former it would be useful to throw at least a warning when the end user is trying to do that. 

```
In [6]: data3.sample_rate
Out[6]: <Quantity 16. Hz>

In [7]: data4 = data3.resample(256)

In [8]: data4.sample_rate
Out[8]: <Quantity 256. Hz>
```

Thanks!

**Comment by alurban** [comment]
@sharanbngr, this is indeed a feature of the `TimeSeries.resample` method. There are lots of cases where you would want to resample a relatively slow timeseries to be able to use it in an operation with a faster one, e.g. in calibration where changes in optical gain are measured at 16 Hz but applied at 4096 Hz. Thus we don't warn the user because it's a perfectly valid use case.

**Comment by sharanbngr** [comment]
@alurban Ah, I see. Thanks!
