### ISSUE TITLE
Data type difference causes irregularities in PSD creation

### ISSUE THREAD

**Issue by GregoryAshton** [gwpy/gwpy#1122]
When using gwpy to read in time-domain hoft data and generating a PSD, there can be some unexpected behaviour. This particular seems to effect Virgo data.

An example. Here I read in 10s of randomly selected Virgo data and then create a psd (note I do this on an LDG cluster so it is using the `fetch` method under the hood. 

```python
from gwpy.timeseries import TimeSeries
V1 = TimeSeries.get('V1:Hrec_hoft_16384Hz_Gated', start=1243530500, end=1243530510)
V1_psd = V1.psd()
fig = V1_psd.plot()
```

The PSD seems to "bottom out" :

![image](https://user-images.githubusercontent.com/1926734/59402038-37363180-8de0-11e9-82ea-dfb7bdcc68af.png)

Notably the `V1_psd` contains a whole bunch of zeros, e.g. `V1_psd[V1_psd == 0]` is non-empty. 

This seems to occur because the data is float32 format.
```python
>>> V1.value
array([1.9750493e-19, 2.7302502e-19, 2.2157778e-19, ...,
       1.5702898e-19, 1.0922566e-19, 1.2618717e-19],
      dtype=float32)
```

This is entirely resolved *if* `dtype='float64'` is added to the get method. 

I suppose there is some reason why the Virgo data defaults to float32 type (note data from the Livingston and Hanford detectors defaults to float64) which is beyond gwpy. But, could there perhaps be a warning in the `psd()` method which warns if the dtype is not of sufficient precision? Or does that even make sense to do?

**Comment by alurban** [comment]
Thanks for posting a ticket @GregoryAshton. You're right that this issue ultimately comes down to numerical precision, and the recommended solution is to enforce 64-bit floats (i.e., double precision) either by passing the `dtype='float64'` keyword argument, or by using the `TimeSeries.astype()` method.

It seems prudent to at least document this issue somewhere, although it's not immediately clear to me where the most natural place for that is. Having the `psd()` method raise a warning is tricky, because in general one can't tell _a priori_ whether a given precision is sufficient, since that will strongly depend on the use case. On the other hand, we could raise warnings when there are zeros in the PSD, but even that is tricky because there are cases where zeros are expected, e.g. when the input has been aggressively bandpassed or truncated.

@duncanmmacleod, what do you think?

**Comment by duncanmmacleod** [comment]
To be blunt, this is not a gwpy issue, is simply relates to users taking care to understand the nature of the data they are working with. We could consider putting a statement in the gwpy online docs somewhere that relates to precision.

**Comment by duncanmmacleod** [comment]
Migrated to https://gitlab.com/gwpy/gwpy/-/issues/1122, please join us on gitlab to continue your contribution!
