### ISSUE TITLE
No FrequencySeriesPlot in GWpy 0.14.1?

### ISSUE THREAD

**Issue by matxil** [gwpy/gwpy#1123]
Hi, 

On one machine, I have pip installed GWpy version 0.9.0 (inside a pycbc installation) and I can use code like: 
`    plot = FrequencySeriesPlot(psd_ts, asd_ts, sep=True, sharex=True, xscale='log', yscale='log', color='green')
`
However, on another machine, also inside a pycbc enviroment, I have GWpy version 0.14.1, and this code gives error: 
`  ImportError: cannot import name FrequencySeriesPlot`
Indeed, with grep, I cannot find this class anywhere in the distribution.
Is there an alternative to this, or should I rewrite the code?

Cheers, 

Machiel

**Comment by duncanmmacleod** [comment]
@matxil, the separate `XxxPlot` classes were removed in an earlier version of gwpy (perhaps 0.14.0), for your usage the alternative is:

```python
from gwpy.plot import Plot
plot = Plot(psd_ts, asd_ts, separate=True, sharex=True, xscale="log", yscale="log", color="green")
```

i.e. the following changes:

- use `Plot` instead of `FrequencySeriesPlot` (or any other `XxxPlot` type)
- use `separate=True` instead of `sep=True`

everything else (I think) is the same.

If this resolves your problem, please close the ticket, otherwise keep posting!

**Comment by matxil** [comment]
Ok, thanks, that fixed it.
