### ISSUE TITLE
 Cannot install gwpy on Windows 10/VisualStudio 2017 becasue of failure in ligo-segments

### ISSUE THREAD

**Issue by SumerMoudgill** [gwpy/gwpy#1127]
I could not 
  pip install gwpy 
because of an error in ligo-segments using Windows 10/VisualStudio 2017.  I have reported the issue and a suggested fix :
https://github.com/duncanmmacleod/ligo-segments/issues/2

**Comment by duncanmmacleod** [comment]
Thanks @SumerMoudgill, the issues `pip` installing `ligo-segments` on windows are known, but so far nobody has been able to work up a fix (the maintainer of `ligo-segments` is not a Windows user and doesn't have time/setup to fix it himself).

Since this isn't strictly a gwpy issue, I will close this ticket, but can offer a temporary solution that using conda to install gwpy should work seamlessly on windows:

```
conda install -c conda-forge gwpy
```

**Comment by SumerMoudgill** [comment]
Sorry, I did not see your respnse until now.
My suggested fix just renames some static functions.  It should be safe
enough to apply.  Should we talk to Dr. Cannon about this?

Thanks,
Sumer

**Comment by duncanmmacleod** [comment]
Yes, please correspond with Kipp to work on ligo-segments.
