### ISSUE TITLE
Apply numpy log function to array data

### ISSUE THREAD

**Issue by SeanDS** [gwpy/gwpy#1249]
I'm grabbing data in a loop:

```python
    alldata = []
    legends = []

    for start, stride in PUMPDOWNS:
        print("Getting data from", tconvert(start))
        data = TimeSeries.get(CHANNEL, start, start+stride, host="our-host", port=8088, verbose=True, pad=np.nan)

        # Reset t0 to 0.
        data.t0 = 0

        alldata.append(np.log(data))
        startdate = tconvert(start)
        legends.append(str(startdate.date()) + " (" + str(stride // 86400) + " days)")

    plt = Plot(alldata, ylim=(1e-7, 1e-5))
    plt.gca().legend(legends)
    plt.show()
```

It complains about the `np.log` call:

```
TypeError: Can only apply 'log' function to dimensionless quantities
```

Ok, so it doesn't like Astropy's units. Converting it to a normal Numpy array though...
```python
alldata.append(np.log(np.array(data)))
```
it complains on the `Plot(...)` line:

```
ValueError: x and y must have same first dimension, but have shapes (8550,) and (11350,)
```

Seems like standard numpy arrays are not compatible with gwpy's plotting routine.
Is there a way to apply natural log scaling (or any other arbitrary functional scaling) to the data while keeping it as a `TimeSeries` object? I can't just use the plot function's xscale because I want a *natural* log.

I also have trouble with the legend. Can I somehow set a label on each timeseries and have the plotter use this automatically without having to call `plt.gca().legend(legends)` with my own list of strings?

BTW is there a LIGO chat channel for gwpy?

**Comment by duncanmmacleod** [comment]
So, there's a few different things in here.

> Ok, so it doesn't like Astropy's units. Converting it to a normal Numpy array though...

The 'correct' way to do this operation is via the `data.value` attribute:

```python
alldata.append(np.log(data.value))
```

> Seems like standard numpy arrays are not compatible with gwpy's plotting routine.

Yes, sort of. What is happening here is that the `Plot` constructor is receiving a few different arrays, which are actually independent data chunks, but because they aren't gwpy `Series` objects (or similar), it just passes them down to `matplotlib` which interprets the list of arrays as the X,Y,X,Y,... axis arrays for half-as-many data sets, hence the eventual `ValueError`.

Onto the actual issue:

> Is there a way to apply natural log scaling (or any other arbitrary functional scaling) to the data while keeping it as a TimeSeries object? I can't just use the plot function's xscale because I want a natural log.

You can directly create a natural-logarithim axis scaling like this:

```python
plot = Plot(...)
ax = plot.gca()
ax.set_yscale('log', basey=np.e)
```

> I also have trouble with the legend. Can I somehow set a label on each timeseries and have the plotter use this automatically without having to call plt.gca().legend(legends) with my own list of strings?

You can't do this automatically while passing data as part of the `Plot()` constructor call. What you will do here is break things out like normal `matplotlib`:

```python
plot = Plot()
ax = plot.gca()
ax.plot(timeseries1, label='mylabel')
...
ax.set_yscale('log', basey=np.e)
```

> BTW is there a LIGO chat channel for gwpy?

Not really. There is a Slack team at gwpy.slack.com but it is almost exclusively used by me only to keep track of development and CI notifications. Most of the users are also on gwdetchar.slack.com, but I am personally most available on chat.ligo.org; there isn't a `gwpy` channel there, but we can start one...

**Comment by duncanmmacleod** [comment]
Regarding taking the logarithm of dimensioned data, see this SO answer:

https://math.stackexchange.com/a/238404

I don't know for sure, but I presume something like this is the motivation for the astropy errors.

**Comment by jaideep11061982** [comment]
how do convert Timeseries object to Numpy form.If i want to apply some numpy function..

**Comment by duncanmmacleod** [comment]
Migrated to https://gitlab.com/gwpy/gwpy/-/issues/1249, please join us on gitlab to continue your contribution!
