### ISSUE TITLE
Time resolution vs frequency resolution with coherence_spectrogram

### ISSUE THREAD

**Issue by areeda** [gwpy/gwpy#1272]
What brought this to light was an attempt to generate a coherence spectrogram over 100s of data with an FFT length of 8 s an overlap of 99%. The minimum  acceptable stride seems to be 16 sec giving us only 9 measurements.

Spectrograms have much better temporal resolution with similar parameters.

Is there a way to get better temporal resolution?

**Comment by alurban** [comment]
@areeda, can you comment on what you mean by "minimum acceptable stride"? With regular spectrograms, there's always a trade-off between stride and overlap because if you shorten either one too much you run the risk of biasing the average. For a regular (i.e., averaged) spectrogram with FFT length 8 sec, the overlap would be 4 sec and 16 sec seems like a perilously short stride.

The only time I can think where I would use an overlap of 99% is with something like the `spectrogram2` method, which doesn't use averages, in which case you can get away with a stride of FFT length - overlap = 0.01 * FFT length. But that use case has major caveats, and at any rate I don't think there's a similar use case for coherence spectrograms -- I think those are always averaged.

**Comment by duncanmmacleod** [comment]
Migrated to https://gitlab.com/gwpy/gwpy/-/issues/1272, please join us on gitlab to continue your contribution!
