### ISSUE TITLE
gwpy.timeseries.TimeSeries.find() does not handle missing data

### ISSUE THREAD

**Issue by tttiago** [gwpy/gwpy#1767]
While using `gwpy.timeseries.TimeSeries.find()` to get Virgo data in the CIT cluster, I have came across the following error:
```
ValueError: 'time (s)' did not parse as unit: Syntax error parsing unit 'time (s)'   
If this is meant to be a custom unit, define it with 'u.def_unit'.  
To have it recognized inside a file reader or other code,  enable it with 'u.add_enabled_units'.  
For details, see https://docs.astropy.org/en/latest/units/combining_and_defining.html
```

This error happens when I try to access Virgo O3a data between `GPS = 1250096000` and  `GPS = 1250104488`. It happens even if I use the argument `pad=0`, which should allow to handle missing data.  
When I use `gwpy.timeseries.TimeSeries.fetch()`, it does not raise an error, and instead returns 0.0 strain for times in the problematic interval. 

----------------

### Steps to reproduce:
```python
from gwpy.timeseries import TimeSeries
channel = "V1:Hrec_hoft_16384Hz"
gps = 1250095993.305
data_cvmfs = TimeSeries.find(channel, gps-32, gps+32).astype("float64")  # fails
data_nds = TimeSeries.find(channel, gps-32, gps+32).astype("float64")  # runs, although data_nds.values are 0.0 
                                                                       # for gps > 1250096000
```

**Comment by duncanmmacleod** [comment]
@tttiago, thanks for the report. This issue is due to bad metadata inside the Virgo h(t) frames for that time interval. The `.fetch()` method uses a different data access method that doesn't attempt to parse the invalid metadata, which is why it doesn't fall over.

This should have been resolved by #1765, due to be released with [GWpy 3.0.8](https://github.com/gwpy/gwpy/milestone/67).

I will close the ticket now, but please reopen if this issue reoccurs after GWpy 3.0.8 is available.
