### ISSUE TITLE
Spectrogram calculation is sub-optimal

### ISSUE THREAD

**Issue by duncanmmacleod** [gwpy/gwpy#25]
The current `Spectrogram` calculation (from a `TimeSeries`) uses non-overlapping chunks, with each one being used to calculate a PSD. This means the edges of each chunk are not represented properly in the overall result, and that the resolution of the resulting `Spectrogram` is low.

We need to rethink the way the `Spectrogram` is calculated, mainly for plotting purposes.

**Comment by duncanmmacleod** [comment]
The current calculation is written up in [/gwpy/spectrogram/spectrogram.py].(https://github.com/gwpy/gwpy/blob/master/gwpy/spectrogram/spectrogram.py)
[[_from_timeseries()](https://github.com/gwpy/gwpy/blob/master/gwpy/spectrogram/spectrogram.py#L41) does the work, [from_timeseries() (no underscore)](https://github.com/gwpy/gwpy/blob/master/gwpy/spectrogram/spectrogram.py#L90) is the wrapper for multiprocessing]

**Comment by areeda** [comment]
A first comment is that we have many resolutions to consider and they all interdependent.  We also have multiple use cases that favor one over the other.

Time resolution is the one Duncan refers to above and seems dominated by the time between FFTs displayed.

Frequency resolution depends on the length of the fft.

Amplitude/Power resolution depends on SNR which depends on the signal and the number of averages.

Contrast resolution (how well we can distinguish between different amplitude/power values) is mainly dependent on how we convert calculated values to display values.

My next comment will try to summarize how ldvw calculates spectrograms which seem to have better time resolution, albeit not without its own set of issues.

**Comment by areeda** [comment]
## Thoughts on maximizing time resolution in FFT based plots

I think the basic conceptual difference between the GWpy spectrogram/coherence spectrogram and the LDVW spectrogram is the time assigned to the Frequency Domain data.

GWpy assigns a time interval to the FD dataset and plots non-overlapping averages, discarding FFTs that cross interval boundries.  LDVW assigns an arbitrary time, currently the start of the interval and plots all ndividual FFTs up to the limit of image resolution.

The GWpy method has better SNR of individual pixels at the expense of time resolution.  Whether the human eye's noise cancellation leverages the better time resolution in ldvw's plots is open for debate.

## Proposal for how to improve time resolution of GWpy Spectrograms

The current parameters controlling GWpy Spectrogram generation are Stride: the length of the time interval, FFT length and Overlap all specified in seconds.

I propose we change the definition of Stride to be the (integer) number of FFTs to average and generate the 2D matrix of ASD/PSD values using all FFTs calculated.

An open issue is what time value to assign to each column of that matrix for plotting.  Since the current GWpy version uses a non-overlapping time interval while this method has those intervals overlapping, possibly a lot.  LDVW's method of assigning the start time of the FFT has the problem of not aligning well with a time series.  A better approach may be to assign the mid point of the time interval.

**Comment by duncanmmacleod** [comment]
I think all of this makes sense. I can code up a new version of the `TimeSeries.spectrogram` method, probably with a different name (e.g. `TimeSeries.spectrogram2`), and post it in a PR for you to take a look at.
