### ISSUE TITLE
Select server for nds transfer based on time of the data

### ISSUE THREAD

**Issue by areeda** [gwpy/gwpy#27]
Data at the sites LLO/LHO are archived to tape after about a month, perhaps 3 weeks.  Data can take hours to retrieve from tape if multiple people are using it.

LDR sometimes gets behind so while data usually arrives at CIT in 10 minutes, we seen it take a week when something nasty happens.

A solution, or at least improvement would be to have the choice of server to try first depend on the age of the data being requested.  A good cut-off value seems to be 2 weeks.  If the data is older than that NDS2 server at CIT should be preferred over the server at the appropriate observatory.

**Comment by duncanmmacleod** [comment]
I've started working on an upgrade to the server selection.

@areeda, should the epoch test override settings in the `NDSSERVER` variable? At the moment, the `NDSSERVER` variable is only implemented in the control rooms, so this question is just asking: should a request for data older than two weeks go to CIT first rather than the local nds1 server?

**Comment by areeda** [comment]
Good question.  It is not a big deal if the server specified is an NDS1 server.  None of its data is on tape so if the time requested is too old a 'requested data not found' error will come back fairly quickly.

My tendency would be to say if the user specifies the order, do what they say.  The problem really only occurs when they ask for data from NDS2 that exists but is on tape and then only a BIG problem if the tape is busy.
