### ISSUE TITLE
LIGO_LW tables should read ASCII/CSV with unified I/O read() method

### ISSUE THREAD

**Issue by duncanmmacleod** [gwpy/gwpy#42]
The `LIGO_LW` format tables imported from `glue` should be able to read space-, tab-, and comma-separated text files using the standard unified `read()` method.

The following simple example works fine for reading CSV and is easily adaptable for other delimiters:

```python
import numpy
from gwpy.table.lsctables import (New, SnglBurstTable)
from gwpy.time import LIGOTimeGPS
trigs = New(SnglBurstTable, columns=['peak_time', 'peak_time_ns', 'snr', 'central_freq'])
for t, f, snr in numpy.loadtxt('mytrigs.csv', delimiter=','):
    row = trigs.RowType()
    row.set_peak(LIGOTimeGPS(float(t)))
    row.central_freq = f
    row.snr = snr
    trigs.append(row)
```

**Comment by areeda** [comment]
that's pretty easy to implement, THANKS!

I wonder if the order of fields in the CSV file should be fixed as t, f, snr?

That is the way I write them, so I like it but I've gotten those files to plot Omega scans in a different order.  Just a suggestion but it might be more general to have a version (maybe the only one) that take 3 parallel arrays rather than assume a format for the file.
