### ISSUE TITLE
Problem making ASD when units are not recognized

### ISSUE THREAD

**Issue by areeda** [gwpy/gwpy#523]
Notebook view https://ldas-jobs.ligo.caltech.edu/~areeda/python/UnitProblem.html
Notebook https://ldas-jobs.ligo.caltech.edu/~areeda/python/UnitProblem.ipynb

When making ASD of channel with units of "Meters/s"
we get:
```WARNING: UnitsWarning: 'Meters/S' did not parse as unit: At col 0, Meters is not a valid unit. Did you mean meter? [astropy.units.core]```
...<snip>
```/Users/areeda/Library/Python/2.7/lib/python/site-packages/gwpy-0.5.2+331.gfd082ce4.dirty-py2.7.egg/gwpy/signal/fft/utils.pyc in scale_timeseries_unit(tsunit, scaling)
     49         raise ValueError("Unknown scaling: %r" % scaling)
     50     if tsunit:
---> 51         specunit = tsunit ** 2 / baseunit
     52     else:
     53         specunit = baseunit ** -1

/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/astropy/units/core.pyc in _unrecognized_operator(self, *args, **kwargs)
   1736         raise ValueError(
   1737             "The unit {0!r} is unrecognized, so all arithmetic operations "
-> 1738             "with it are invalid.".format(self.name))
   1739 
   1740     __pow__ = __div__ = __rdiv__ = __truediv__ = __rtruediv__ = __mul__ = \

ValueError: The unit u'Meters/S' is unrecognized, so all arithmetic operations with it are invalid.```

**Comment by duncanmmacleod** [comment]
@areeda, this seems like something that should be fixed, but I am having trouble reproducing this. What version of the nds2-client is required? When I query from the CIT computing centre with 0.14.2 I get:

```python
>>> import nds2
>>> conn = nds2.connection('nds-dev.ligo.caltech.edu')
>>> conn.fetch(1176768018, 1176768018+100, ['L1:PEM-EX_WIND_WEATHER_MPS'])[0].signal_units
''
```

**Comment by areeda** [comment]
You would have to build the client from sources and pull from nds-dev.ligo.caltech.edu
It's actually a protocol change that's negotiated so server and client are new.  Scheduled for release before O3.

**Comment by duncanmmacleod** [comment]
@areeda, I managed to build the NDS2 client from SVN and can reproduce the error. However, I'm not sure what the best solution for this problem is. There are two options I can think of:

1. Don't fix it, if people use invalid units, they can't expect anything to work
2. Patch the unit parser for the `TimeSeries` object to reject anything that is doesn't recognise and return `undef` instead, this means arithmetic operations will work, but units don't get carried along.

I think the second option is the only practical one.

At the same time I want to shout at the LIGO Lab for using `Meters/S` as the unit, which, even after I patch the parser to match `Meters` -> `meter`, still comes out as `meter/siemens`.

**Comment by areeda** [comment]
Let me know if you have problems building from sources. Attached is the script I use on my Mac.
[updateNdsMac.zip](https://github.com/gwpy/gwpy/files/1242911/updateNdsMac.zip)
Yo will have to edit paths.

you also have to add the following line to /opt/local/etc/macports/sources.conf:
file:///Users/areeda/build/nds2-client/test_port [nosync]

It's not hard to unwind when you want to go back to released software.
