### ISSUE TITLE
Move to BSD license

### ISSUE THREAD

**Issue by duncanmmacleod** [gwpy/gwpy#965]
I would like to consider moving gwpy to a BSD-style license, away from GPL, mainly after reading [this post](http://nipy.sourceforge.net/software/license/johns_bsd_pitch.html) from John Hunter (creator of Matplotlib).

cc @gwpy/gwpy-developers

**Comment by alurban** [comment]
@duncanmmacleod, John's argument is pretty convincing, maybe this is something we should look into?

**Comment by jrollins** [comment]
I don't have any particular problem with BSD licenses, but I'm not necessarily convinced by this argument.  I doubt that gwpy is losing much "mind share" from the private sector.

Also, this point begs the question:
```
There is a lot of GPLd code in the world, and it is a constant reality in the development of matplotlib that when we want to reuse some algorithm, we have to go on a hunt for a non-GPLd version.
```
The reason they have to go on the hunt for non-GPL code is because they made their code non-GPL.  So that's not some inherent problem with GPL code.

**Comment by duncanmmacleod** [comment]
Migrated to https://gitlab.com/gwpy/gwpy/-/issues/965, please join us on gitlab to continue your contribution!
